name: Mp3projects
version: '${project.version}'
main: com.crumbed.mp3projects.Mp3projects
api-version: 1.20
authors: [ Crumbed ]
depend: [ Multiverse-Core ]
description: Mp3 projects plugin
commands:
  craft:
    usage: /craft
  echest:
    aliases: [ ec, enderchest ]
    usage: /ec
  resource_world:
    aliases: [ reworld, rworld, altworld ]
    usage: /rworld